Add system.stdout.isTTY property
ariya/phantomjs pull request #14578
Opened 2016-10-07 17:12 UTC by tylfin

Add test isTTY test in system.js
https://github.com/ariya/phantomjs/issues/13454

2016-10-15 15:02 UTC, Vitallium commented
Check list:
- [ ] Linux
- [ ] OS X
- [ ] Windows

2016-10-15 15:03 UTC, vitallium requested changes

2016-10-15 15:03 UTC, Vitallium commented on src/filesystem.h
> +#include <stdio.h>
You don't need this header here. You can omit it.

2016-10-18 02:16 UTC, tylfin commented on src/filesystem.h
> +#include <stdio.h>
Taken care of

2017-12-19 22:05 UTC, merged